-- 코드를 입력하세요
select B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, date_format(R.CREATED_DATE, "%Y-%m-%d") as CREATED_AT
from USED_GOODS_BOARD as B join USED_GOODS_REPLY as R
on B.BOARD_ID = R.BOARD_ID
where year(B.CREATED_DATE) = 2022 AND month(B.CREATED_DATE) = 10
order by R.CREATED_DATE ASC, B.TITLE ASC